name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Print go env
        run: |
          go env
          echo "PATH: ${PATH}"

      - name: Test
        run: go test -v ./...

      - name: Staticcheck
        run: |
          go get -v -u honnef.co/go/tools/cmd/staticcheck
          export GOBINPATH=`go env GOPATH`/bin
          export PATH="${PATH}:${GOBINPATH}"
          ls -lah `go env GOPATH`
          ls -lah `go env GOPATH`/bin
          staticcheck ./...
